# Logo (Font Awesome Class)
fa_logo: fa-cube

# Header
menu:
  Home: /
  Archives: /archives
  About: /about.html
  Contact: /contact.html

# Default post title
default_post_title: Untitled

# Archive Date Format
archive_date_format: MMM YYYY

# Comments.
comments:
  # Disqus comments
  disqus_shortname: Legendary Nacar

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/legendarynacar/
facebook_url: https://www.facebook.com/LegendaryNacar/
instagram_url: https://www.instagram.com/legendarynacar/
dribble_url: 
github_url: https://github.com/legendarynacar
googleplus_url: 
behance_url: 
fivehundredpx_url: 
email_url: legendarynacar@gmail.com
rss_url: \#

# Footer About Text
footer_about: "This theme was developed by <a href=\"https://github.com/klugjo\">Jonathan Klughertz</a>. The source code is available on Github. Create Websites. Make Magic."

# Footer Copyright Line
footer_copyright: "@Untitled. All right reserved | Design & Hexo <a href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"

